/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SellRouteImport } from './routes/sell'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSteamRouteImport } from './routes/api/auth/steam'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiPublicInventorySteamIdRouteImport } from './routes/api/public/inventory.$steamId'
import { Route as ApiAuthSteamCallbackRouteImport } from './routes/api/auth/steam.callback'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSteamRoute = ApiAuthSteamRouteImport.update({
  id: '/api/auth/steam',
  path: '/api/auth/steam',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInventorySteamIdRoute =
  ApiPublicInventorySteamIdRouteImport.update({
    id: '/api/public/inventory/$steamId',
    path: '/api/public/inventory/$steamId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSteamCallbackRoute = ApiAuthSteamCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthSteamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/my-listings': typeof MyListingsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/steam': typeof ApiAuthSteamRouteWithChildren
  '/api/auth/steam/callback': typeof ApiAuthSteamCallbackRoute
  '/api/public/inventory/$steamId': typeof ApiPublicInventorySteamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/my-listings': typeof MyListingsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/steam': typeof ApiAuthSteamRouteWithChildren
  '/api/auth/steam/callback': typeof ApiAuthSteamCallbackRoute
  '/api/public/inventory/$steamId': typeof ApiPublicInventorySteamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/my-listings': typeof MyListingsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/steam': typeof ApiAuthSteamRouteWithChildren
  '/api/auth/steam/callback': typeof ApiAuthSteamCallbackRoute
  '/api/public/inventory/$steamId': typeof ApiPublicInventorySteamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/inventory'
    | '/my-listings'
    | '/sell'
    | '/settings'
    | '/trades'
    | '/watchlist'
    | '/api/auth/logout'
    | '/api/auth/steam'
    | '/api/auth/steam/callback'
    | '/api/public/inventory/$steamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/inventory'
    | '/my-listings'
    | '/sell'
    | '/settings'
    | '/trades'
    | '/watchlist'
    | '/api/auth/logout'
    | '/api/auth/steam'
    | '/api/auth/steam/callback'
    | '/api/public/inventory/$steamId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/inventory'
    | '/my-listings'
    | '/sell'
    | '/settings'
    | '/trades'
    | '/watchlist'
    | '/api/auth/logout'
    | '/api/auth/steam'
    | '/api/auth/steam/callback'
    | '/api/public/inventory/$steamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  InventoryRoute: typeof InventoryRoute
  MyListingsRoute: typeof MyListingsRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  TradesRoute: typeof TradesRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSteamRoute: typeof ApiAuthSteamRouteWithChildren
  ApiPublicInventorySteamIdRoute: typeof ApiPublicInventorySteamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/steam': {
      id: '/api/auth/steam'
      path: '/api/auth/steam'
      fullPath: '/api/auth/steam'
      preLoaderRoute: typeof ApiAuthSteamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inventory/$steamId': {
      id: '/api/public/inventory/$steamId'
      path: '/api/public/inventory/$steamId'
      fullPath: '/api/public/inventory/$steamId'
      preLoaderRoute: typeof ApiPublicInventorySteamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/steam/callback': {
      id: '/api/auth/steam/callback'
      path: '/callback'
      fullPath: '/api/auth/steam/callback'
      preLoaderRoute: typeof ApiAuthSteamCallbackRouteImport
      parentRoute: typeof ApiAuthSteamRoute
    }
  }
}

interface ApiAuthSteamRouteChildren {
  ApiAuthSteamCallbackRoute: typeof ApiAuthSteamCallbackRoute
}

const ApiAuthSteamRouteChildren: ApiAuthSteamRouteChildren = {
  ApiAuthSteamCallbackRoute: ApiAuthSteamCallbackRoute,
}

const ApiAuthSteamRouteWithChildren = ApiAuthSteamRoute._addFileChildren(
  ApiAuthSteamRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  InventoryRoute: InventoryRoute,
  MyListingsRoute: MyListingsRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  TradesRoute: TradesRoute,
  WatchlistRoute: WatchlistRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSteamRoute: ApiAuthSteamRouteWithChildren,
  ApiPublicInventorySteamIdRoute: ApiPublicInventorySteamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
